### ISSUE TITLE
deid version option has a bug

### ISSUE THREAD

**Issue by vsoch** [pydicom/deid#75]
Running the container reveals:

```bash
(base) root@4abd1befe0c8:/code# which deid
/opt/conda/bin/deid
(base) root@4abd1befe0c8:/code# deid
Traceback (most recent call last):
  File "/opt/conda/bin/deid", line 11, in <module>
    load_entry_point('deid==0.1.19', 'console_scripts', 'deid')()
  File "/opt/conda/lib/python3.6/site-packages/deid-0.1.19-py3.6.egg/deid/main/__init__.py", line 141, in main
    if args.command == "version" or args.version is True:
AttributeError: 'Namespace' object has no attribute 'version'
```

**Comment by vsoch** [comment]
Fixed
